### ISSUE TITLE
Early-process Overhauls ˖*°࿐

### ISSUE THREAD

**Issue by briannededeugd** [briannededeugd/tumimundo#13]
_Hey team,_ 👋🏽

I just returned from a tech feedback sesh. Coach suggested we do two types of overhaul to maximize our efficiency:

### 🪵. *. ⋆  Branch system overhaul

We're currently operating with branches named after our literal names, meaning we have our own little spaces to work in. But the custom is actually to name branches after certain features, Cyd says to allow us to work on things simultaneously (though I'll have to ask how, exactly). Is this something we're willing to do/change right now?

___

### 📂 ₊ ⊹ ⋆⁺ Folder and directory overhaul

In theory this shouldn't be a big deal, but this is about the `tumi-mundo` folder we have inside of our `tumimundo` root, it's unnecessary 🙃 Are we okay to move it all to the root?? Is this something I should test out on my branch (or perhaps a new test branch??) LMK.

That's all, byeeee 💋

**Comment by rosemulazada** [comment]
Hi Brianne! 🙋🏻‍♀️

Good to hear about your findings during the feedback rounds. As I also had Cyd for my review, I decided to take your questions with me so we can come to a decision on what the next best steps are.

### 𖠰 || Branch system overhaul
I mentioned this to Cyd when I displayed our GitHub. She told me that working with features as branches is more efficient because, besides what she mentioned to you, it allows you to create more tasks than there are developers in our team. Also, once a task is completed, you can close a branch. This would not be the case if we used our names as branches. This means we get a free checklist, so to speak, and closing those branches does sound pretty satisfying.. 

Maybe we can also add our names after the branch name to keep track of who's on which task, though that might mean the branch names will be quite a mouthful. Just a thought.

_To the others, what do you think? Sounds good or no?_ 🤔💭

***

### ⫘ || Folder & directory overhaul

I've made that mistake countless times.. it's because we committed the folder created by SvelteKit, instead of doing ```cd tumi-mundo``` first. I say, navigate into the map locally and see if all works as it should. I don't know what effect it will have because ```git``` is initialised in the parent folder (I think). But nothing we can't fix. Maybe worth looking into. 

Good work! Looking forward to hearing from you and the others soon. ☺️

**Comment by Sensinki** [comment]
Heyy,
I'm glad to hear these findings, I had never thought about it.

### 𖠰 || Branch system overhaul

Honestly, I like this idea. I have seen other companies that work with large groups also work with branches in this way. Also, as Rose said, the fact that we can use it as a checklist is a big plus and really satisfaying :)

### ⫘ || Folder & directory overhaul

I had a little bit of difficulty with this, but now that I'm used to it. I also don't know exactly how because I don't have much experience in this subject. I will follow the majority's decision on this issue.

❤️❤️❤️

**Comment by lainecedes** [comment]
> ### 𖠰 || Branch system overhaul
> Honestly, I like this idea. I have seen other companies that work with large groups also work with branches in this way. Also, as Rose said, the fact that we can use it as a checklist is a big plus and really satisfaying :)
> 
> ### ⫘ || Folder & directory overhaul
> I had a little bit of difficulty with this, but now that I'm used to it. I also don't know exactly how because I don't have much experience in this subject. I will follow the majority's decision on this issue.
> 
> ❤️❤️❤️

Aye, 

The branch system could work better for us for professional reasons. In case 1 people need to work together on one branch, we can use the plugin 'Live Share' from VS Code itself where someone can create a collaboration session link to join in. Note: Make sure that you're in the designated branch and don't switch when you're in the middle of collaborating. 

And the folder & directory overhaul can be changed, but I fear we'll get some conflicts in the code regarding using relative paths and so on. Someone is needed to edit and double these paths to make sure that everything still works..

ANYWAYS GOOD WORK GUYS LFG TEAM

**Comment by briannededeugd** [comment]
@lainecedes you're so right. Let's modify the branch names and make sure we all use Live Share. Maybe the folder & directory overhaul is something for later? I don't think it's a huge priority right now.

**Comment by rosemulazada** [comment]
I think we can leave it, for now. It's not impacting our work. It's just nice to fix at any point. Good work and thanks to Brianne for addressing this! I'll close this issue now :)
